Repository vultr/vultr-cli, pull requests merged in 2019-08, with the labels that each got.

#41 Fix #40 - Add quotes to dns data
  cmd/dnsRecord.go
Labels: bug

#42 release for v0.1.3
  CHANGELOG.md
  cmd/version.go
Labels: release

#44 added in gofmt in the makefile
  Makefile
Labels: enhancement

#43 added script contents command, cleaned up script list output
  cmd/printer/script.go
  cmd/script.go
Labels: enhancement

#45 release v0.1.4
  CHANGELOG.md
  cmd/version.go
Labels: release
