Repository vultr/vultr-cli, pull requests merged in 2019-12, with the labels that each got.

#65 Network error msg
  cmd/network.go
Labels: bug

#66 Release 0.1.11
  CHANGELOG.md
  cmd/version.go
Labels: release

#69 Simplify the Makefile to make it more portable
  GNUmakefile
  Makefile
Labels: enhancement
