Repository vultr/vultr-cli, pull requests merged in 2020-04, with the labels that each got.

#86 BlockStorage live attach/detach
  cmd/blockStorage.go
  go.mod
  go.sum
  vendor/github.com/vultr/govultr/CHANGELOG.md
  vendor/github.com/vultr/govultr/block_storage.go
  vendor/github.com/vultr/govultr/govultr.go
  vendor/modules.txt
Labels: enhancement

#88 enhance server create behavior
  cmd/server.go
Labels: enhancement

#89 Newlines cleanup
  cmd/apiKey.go
  cmd/blockStorage.go
  cmd/iso.go
  cmd/script.go
  cmd/server.go
  go.sum
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/viper/go.mod
  vendor/github.com/spf13/viper/go.sum
  vendor/modules.txt
Labels: dependencies, enhancement

#90 release for v0.3.0
  CHANGELOG.md
  cmd/version.go
Labels: release
