Repository vultr/vultr-cli, pull requests merged in 2023-08, with the labels that each got.

#334 Update govultr to v3.3.0
  go.mod
  go.sum
Labels: dependencies

#335 Add support for VPC 2.0
  README.md
  cmd/bareMetal.go
  cmd/database.go
  cmd/instance.go
  cmd/printer/bareMetal.go
  cmd/printer/instance.go
  cmd/printer/vpc2.go
  cmd/root.go
  cmd/vpc2.go
Labels: enhancement

#336 Add more aliases for the apps command
  cmd/application.go
Labels: enhancement

#337 cmd/instance: Fix reserved IPv4 flag docs
  cmd/instance.go
Labels: documentation

#338 Update govultr to v3.3.1
  go.mod
  go.sum
Labels: dependencies

#339 VPC2 Nodes Endpoints
  cmd/printer/vpc2.go
  cmd/vpc2.go
Labels: enhancement

#340 Managed Database Nesting Refactor
  cmd/database.go
Labels: enhancement

#341 Release v2.18.0 #minor
  CHANGELOG.md
  cmd/version.go
Labels: release

#342 Remove replacement and use name template in goreleaser archives
  .goreleaser.yml
Labels: automation

#343 Release v2.18.1 #patch
  CHANGELOG.md
  cmd/version.go
Labels: release

#345 Release v2.18.2 #patch
  CHANGELOG.md
  cmd/version.go
Labels: release

#346 Add project name back to the archive file names in goreleaser
  .goreleaser.yml
Labels: automation
