Repository vultr/vultr-cli, pull requests merged in 2023-10, with the labels that each got.

#355 Rework the printer output code
  .golangci.yaml
  cmd/dnsRecord.go
  cmd/printer/account.go
  cmd/printer/application.go
  cmd/printer/backup.go
  cmd/printer/bareMetal.go
  cmd/printer/billing.go
  cmd/printer/blockStorage.go
  cmd/printer/database.go
  cmd/printer/dnsDomain.go
  cmd/printer/dnsRecord.go
  cmd/printer/firewallGroup.go
  cmd/printer/firewallRule.go
  cmd/printer/instance.go
  cmd/printer/iso.go
  cmd/printer/kubernetes.go
  cmd/printer/loadBalancer.go
  cmd/printer/network.go
  cmd/printer/objectStorage.go
  cmd/printer/os.go
  cmd/printer/plans.go
  cmd/printer/printer.go
  cmd/printer/regions.go
  cmd/printer/reservedIP.go
  cmd/printer/script.go
  cmd/printer/snapshot.go
  cmd/printer/ssh-key.go
  cmd/printer/user.go
  cmd/printer/userData.go
  cmd/printer/vpc.go
  cmd/printer/vpc2.go
Labels: enhancement

#360 Release v2.19.0 #minor
  CHANGELOG.md
  cmd/version.go
Labels: release

#362 Update govultr to v3.3.2
  go.mod
  go.sum
Labels: dependencies

#363 Managed Database public/private hostnames, cleanup summarize view
  cmd/printer/database.go
Labels: enhancement

#365 Update govultr to v3.3.3
  cmd/database.go
  go.mod
  go.sum
Labels: dependencies

#366 Adjust DBaaS VPC pointer to detect changes
  cmd/database.go
Labels: bug

#364 Allow some commands to be run without authenticating against the API
  cmd/account.go
  cmd/backups.go
  cmd/bareMetal.go
  cmd/billing.go
  cmd/blockStorage.go
  cmd/database.go
  cmd/dns.go
  cmd/firewall.go
  cmd/instance.go
  cmd/iso.go
  cmd/kubernetes.go
  cmd/loadBalancer.go
  cmd/network.go
  cmd/objectStorage.go
  cmd/reservedIP.go
  cmd/root.go
  cmd/script.go
  cmd/snapshot.go
  cmd/sshKey.go
  cmd/user.go
  cmd/vpc.go
  cmd/vpc2.go
Labels: enhancement

#367 Update govultr to v3.3.4
  go.mod
  go.sum
Labels: dependencies

#368 Add support for the VKE HA control plane option
  cmd/kubernetes.go
  cmd/printer/kubernetes.go
Labels: enhancement
