Repository vultr/vultr-cli, pull requests merged in 2023-09, with the labels that each got.

#347 Update to go v1.21
  Dockerfile
  go.mod
  go.sum
Labels: dependencies

#348 Add summarize list options for VKE, VLB & database
  cmd/database.go
  cmd/kubernetes.go
  cmd/loadBalancer.go
  cmd/printer/database.go
  cmd/printer/kubernetes.go
  cmd/printer/loadBalancer.go
Labels: enhancement

#97 Remove unnecessary Go dependency from .goreleaser
  .goreleaser.yml
Labels: automation

#349 Remove the useless cobra init help toggle flag
  cmd/root.go
Labels: bug

#350 Doc fixes
  cmd/vpc2.go
Labels: documentation

#353 Add golangci-lint and fix linter errors
  .github/workflows/coverage.yml
  .github/workflows/gochecks.yml
  .github/workflows/releaser.yml
  .golangci.yaml
  cmd/application.go
  cmd/backups.go
  cmd/bareMetal.go
  cmd/bareMetalUserData.go
  cmd/billing.go
  cmd/blockStorage.go
  cmd/database.go
  cmd/dnsDomain.go
  cmd/dnsRecord.go
  cmd/firewallGroup.go
  cmd/firewallRule.go
  cmd/instance.go
  cmd/iso.go
  cmd/kubernetes.go
  cmd/loadBalancer.go
  cmd/network.go
  cmd/objectStorage.go
  cmd/os.go
  cmd/plans.go
  cmd/plansMetal.go
  cmd/printer/kubernetes.go
  cmd/printer/vpc2.go
  cmd/regions.go
  cmd/reservedIP.go
  cmd/root.go
  cmd/script.go
  cmd/snapshot.go
  cmd/sshKey.go
  cmd/user.go
  cmd/vpc.go
  cmd/vpc2.go
Labels: automation
