Repository vultr/vultr-cli, pull requests merged in 2023-11, with the labels that each got.

#369 Add Support for DBaaS FerretDB Subscriptions
  cmd/printer/database.go
Labels: enhancement

#370 Release v2.20.0 #minor
  CHANGELOG.md
  cmd/version.go
Labels: release

#372 Update the bare-metal and instance tags display to use delimiters
  cmd/printer/bareMetal.go
  cmd/printer/instance.go
  cmd/printer/printer.go
Labels: enhancement

#374 Bump govultr to v3.4.0
  go.mod
  go.sum
Labels: dependencies

#375 Support Managed Database Read Replica Promotion
  cmd/database.go
Labels: enhancement

#361 add kubeconfig filepath flag
  cmd/kubernetes.go
Labels: enhancement

#376 Update govultr to v3.4.1
  go.mod
  go.sum
Labels: dependencies

#378 Add Managed Database Usage Endpoint Support
  cmd/database.go
  cmd/printer/database.go
Labels: enhancement

#380 Add container registry
  README.md
  cmd/containerRegistry.go
  cmd/printer/containerRegistry.go
  cmd/root.go
Labels: enhancement

#381 Release v2.21.0 #minor
  CHANGELOG.md
  cmd/version.go
Labels: release
