Repository vultr/vultr-cli, pull requests merged in 2024-06, with the labels that each got.

#452 Update govultr from v2.7.0 to v2.8.1
  go.mod
  go.sum
Labels: dependencies

#453 Support Vultr Serverless Inference
  README.md
  cmd/inference/inference.go
  cmd/inference/printer.go
  cmd/root.go
Labels: enhancement

#455 Ignore linux binary
  .gitignore
Labels: automation

#456 Update goreleaser config and action
  .github/workflows/releaser.yml
  .goreleaser.yml
Labels: automation

#457 Linter updates and fixes
  .golangci.yaml
  cmd/applications/applications.go
  cmd/backups/backups.go
  cmd/baremetal/baremetal.go
  cmd/billing/billing.go
  cmd/blockstorage/blockstorage.go
  cmd/containerregistry/containerregistry.go
  cmd/containerregistry/printer.go
  cmd/database/database.go
  cmd/dns/dns.go
  cmd/firewall/firewall.go
  cmd/instance/instance.go
  cmd/iso/iso.go
  cmd/kubernetes/kubernetes.go
  cmd/loadbalancer/loadbalancer.go
  cmd/loadbalancer/printer.go
  cmd/objectstorage/objectstorage.go
  cmd/operatingsystems/operatingsystems.go
  cmd/plans/plans.go
  cmd/regions/regions.go
  cmd/reservedip/reservedip.go
  cmd/script/script.go
  cmd/sshkeys/sshKeys.go
  cmd/users/user.go
  cmd/vpc/vpc.go
  cmd/vpc2/vpc2.go
Labels: automation

#459 Update the go-checks actions
  .github/workflows/gochecks.yml
Labels: automation

#458 Release v3.2.0 #minor
  CHANGELOG.md
  cmd/version/version.go
Labels: release

#461 Update govultr from v3.8.1 to v3.9.0
  go.mod
  go.sum
Labels: dependencies
