Repository vultr/vultr-cli, pull requests merged in 2024-02, with the labels that each got.

#396 Release v2.22.0 #minor
  CHANGELOG.md
  cmd/version.go
Labels: release

#404 Release v3.0.0 #major
  CHANGELOG.md
  cmd/version/version.go
Labels: release

#405 Update go get command to v3.
  README.md
Labels: documentation

#406 Remove shorthand flag output on kubernetes
  cmd/kubernetes/kubernetes.go
Labels: regression

#413 Add kubernetes `enable-firewall` flag on create
  cmd/kubernetes/kubernetes.go
  cmd/kubernetes/printer.go
Labels: enhancement

#414 Add correct usage for firewall rules
  cmd/firewall/firewall.go
Labels: documentation

#410 Consolidate pagination metadata nil pointer checks
  cmd/applications/printer.go
  cmd/backups/printer.go
  cmd/baremetal/printer.go
  cmd/billing/printer.go
  cmd/blockstorage/printer.go
  cmd/containerregistry/printer.go
  cmd/dns/printer.go
  cmd/firewall/printer.go
  cmd/instance/printer.go
  cmd/ip/printer.go
  cmd/iso/printer.go
  cmd/kubernetes/printer.go
  cmd/loadbalancer/printer.go
  cmd/objectstorage/printer.go
  cmd/operatingsystems/printer.go
  cmd/plans/printer.go
  cmd/printer/printer.go
  cmd/regions/printer.go
  cmd/reservedip/printer.go
  cmd/script/printer.go
  cmd/snapshot/printer.go
  cmd/sshkeys/printer.go
  cmd/users/printer.go
  cmd/vpc/printer.go
  cmd/vpc2/printer.go
Labels: enhancement

#415 Release v3.0.1 #patch
  CHANGELOG.md
  cmd/version/version.go
Labels: release

#416 Fix inadvertent short-circuiting bare metal plan printer
  cmd/plans/plans.go
  cmd/plans/printer.go
Labels: bug

#417 Update govultr from v3.6.2 to v3.6.3
  go.mod
  go.sum
Labels: dependencies
