Repository vultr/vultr-cli, pull requests merged in 2024-10, with the labels that each got.

#475 Fix command to install vultr-cli using Go
  README.md
Labels: documentation

#477 Update README.md
  README.md
Labels: documentation

#482 Remove deprecated exportloopref linter
  .golangci.yaml
Labels: automation

#484 Add github CODEOWNERS file
  .github/CODEOWNERS
Labels: automation

#485 Update govultr from v3.11.0 to v3.11.1
  go.mod
  go.sum
Labels: dependencies

#486 Update govultr from v3.11.1 to v3.11.2
  go.mod
  go.sum
Labels: dependencies

#487 Support Managed Kafka
  cmd/database/database.go
  cmd/database/printer.go
Labels: enhancement

#488 Release v3.4.0 #minor
  CHANGELOG.md
  cmd/version/version.go
Labels: release
