Repository vultr/vultr-cli, pull requests merged in 2024-03, with the labels that each got.

#419 Make command Run error return consistent
  cmd/account/account.go
  cmd/backups/backups.go
  cmd/baremetal/baremetal.go
  cmd/billing/billing.go
  cmd/blockstorage/blockstorage.go
  cmd/containerregistry/containerregistry.go
  cmd/dns/dns.go
  cmd/firewall/firewall.go
  cmd/iso/iso.go
  cmd/kubernetes/kubernetes.go
  cmd/objectstorage/objectstorage.go
  cmd/printer/error.go
  cmd/printer/generic.go
  cmd/printer/info.go
  cmd/printer/message.go
  cmd/vpc/vpc.go
  cmd/vpc2/vpc2.go
Labels: enhancement

#421 Update govultr from v3.6.3 to v3.6.4
  go.mod
  go.sum
Labels: dependencies

#422 Add node labels to kubernetes node pools
  cmd/kubernetes/kubernetes.go
  cmd/kubernetes/printer.go
Labels: enhancement

#425 Remove extraneous readme details
  README.md
Labels: documentation

#426 Fix incorrect govultr delete method for VPC2
  cmd/vpc2/vpc2.go
Labels: regression

#427 Release v3.0.2 #patch
  CHANGELOG.md
  cmd/version/version.go
Labels: release

#430 Fix oauth token when a config file is used
  pkg/cli/cli.go
Labels: regression

#431 Release v3.0.3 #patch
  CHANGELOG.md
  cmd/version/version.go
Labels: release

#432 fix mistyped persistent_pxe baremetal flag
  cmd/baremetal/baremetal.go
Labels: bug, regression

#434 Fix error when a config file is not present
  cmd/root.go
Labels: regression
