Repository vultr/vultr-cli, pull requests merged in 2025-07, with the labels that each got.

#543 Managed Databases: Add Expanded Support for Kafka Features
  cmd/database/database.go
  cmd/database/printer.go
Labels: enhancement

#545 Update govultr from v3.21.0 to v3.21.1
  go.mod
  go.sum
Labels: dependencies

#546 Release v3.6.0 #minor
  CHANGELOG.md
  cmd/version/version.go
Labels: release
