Repository vultr/vultr-cli, pull requests merged in 2025-03, with the labels that each got.

#515 Update go to v1.24
  .github/workflows/gochecks.yml
  .github/workflows/releaser.yml
  go.mod
Labels: dependencies, automation

#516 Update govultr from v3.14.1 to v3.15.0
  go.mod
  go.sum
Labels: dependencies

#517 Set global options on account command
  cmd/account/account.go
Labels: bug

#518 Remove coverage workflow
  .github/workflows/coverage.yml
Labels: automation

#506 Added missing args check in commands
  cmd/containerregistry/containerregistry.go
  cmd/database/database.go
  cmd/kubernetes/kubernetes.go
Labels: bug

#524 Update govultr from v3.15.0 to v3.17.0
  cmd/baremetal/baremetal.go
  cmd/instance/instance.go
  cmd/objectstorage/objectstorage.go
  cmd/vpc2/vpc2.go
  go.mod
  go.sum
Labels: dependencies

#525 Mark vpc2 commands deprecated
  cmd/baremetal/baremetal.go
  cmd/instance/instance.go
  cmd/vpc2/vpc2.go
Labels: documentation

#526 Fix err nil checks
  cmd/baremetal/baremetal.go
  cmd/dns/dns.go
  cmd/kubernetes/kubernetes.go
Labels: bug
